name: 'Crawler'

on:
  schedule:
    - cron: '0 22 * * *'  # UTC时间14点（北京时间22点）
  push:
    branches:
      - main
 
  
jobs:
  arxiv-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set time zone'
        run: echo "TZ='Asia/Shanghai'" >> $GITHUB_ENV  # 更安全的时区设置方式

      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # 使用支持的版本

      - name: 'Install requirements'
        run: pip install -r ./requirements.txt

      - name: 'Crawl'
        run: python arXiv/process.py

      - name: 'Detect changes'
        id: detect_changes
        run: if [ -n "$(git status --porcelain)" ]; then echo "changes_detected=yes" >> $GITHUB_OUTPUT; fi

      - name: 'Push changes'
        if: steps.detect_changes.outputs.changes_detected == 'yes'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "* update `date '+%Y-%m-%d %H:%M:%S'`"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
